<a href="https://colab.research.google.com/github/THEJAASHREE/231801181-Gen-AI/blob/main/MODEL_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

def one_hot_encode(text):
    words = text.lower().split()
    vocab = sorted(set(words))
    word_to_int = {word: i for i, word in enumerate(vocab)}

    data = []
    for word in words:
        vector = [0] * len(vocab)
        vector[word_to_int[word]] = 1
        data.append(vector)
    return np.array(data), vocab

data, vocab = one_hot_encode("AI ML DL AI NLP ML")
print("vocab:",vocab)
print(data)

vocab: ['ai', 'dl', 'ml', 'nlp']
[[1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]]
